os: osx
osx_image: xcode61
language: objective-c
before_install:
- brew update 2>&1 > /dev/null
- brew install --build-from-source libusb 2>&1 > /dev/null
- brew install qt5 2>&1 > /dev/null
- brew link qt5 --force
before_script: /usr/local/opt/qt5/bin/qmake
script:
- make
- /usr/local/opt/qt5/bin/macdeployqt pp2trayer.app -always-overwrite -verbose=2
- curl -o /tmp/macdeployqtfix.py https://raw.githubusercontent.com/aurelien-rainone/macdeployqtfix/master/macdeployqtfix.py
- python /tmp/macdeployqtfix.py ./pp2trayer.app/Contents/MacOS/pp2trayer /usr/local/Cellar/qt5/5.5.0_1/
- /usr/local/opt/qt5/bin/macdeployqt pp2trayer.app -dmg -no-plugins
- mkdir deploy
- cp pp2trayer.dmg deploy
deploy:
  provider: s3
  access_key_id: AKIAJIUMJWTHBLSLXXPA
  secret_access_key:
    secure: ES84SEZiF04qowtY18cH5JCjAVjXb7euENL3KDklQJB8Bvj/8lJegRoalrdTabEUs9sc9Ys/J7MPaxqAZZO+uNFtNRQAHAzkyu1Kt39Gzv9vpOaqPuRndwx7M6xycpkL43dZIBe9rIv++Ru0GPenBPmlAGDUArsJwFRXqBuL7iQ=
  bucket: pixelpulse2trayer
  skip_cleanup: true
  local_dir: deploy
  acl: public_read
  on:
    repo: analogdevicesinc/Pixelpulse2-Trayer
    all_branches: true
