os: Windows Server 2012 R2
platform:
 - x86

install:
  - ps: (new-object System.Net.WebClient).Downloadfile("http://sourceforge.net/projects/mingw-w64/files/External%20binary%20packages%20%28Win64%20hosted%29/MSYS%20%2832-bit%29/MSYS-20111123.zip", "c:\msys.zip")
  - 7z x -y "c:\msys.zip" -o"C:\" > nul
  - set MINGW_PATH=C:\Qt\Tools\mingw530_32
  - set QTDIR=C:\Qt\5.10\mingw53_32
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%MINGW_PATH%\bin;C:\msys\bin\;%QTDIR%\bin;%PATH%
  - ps: (new-object System.Net.WebClient).Downloadfile("http://swdownloads.analog.com/cse/build/libusb-1.0-hp.7z", "c:\libusb.7z")
  - 7z x -y "c:\libusb.7z" -o"C:\libusb" > nul

build_script:
  - git submodule update --init --recursive
  - qmake pp2trayer.pro
  - mingw32-make -j8

after_build:
- ps: |
    If (!(Test-Path -Path "distrib.zip")) {
      windeployqt --qmldir qml release\pp2trayer.exe --dir distrib
      7z a -y distrib.zip distrib
    }
    appveyor PushArtifact release\pp2trayer.exe
    appveyor PushArtifact distrib.zip

cache:
 - distrib.zip -> pp2trayer.pro
 - c:\msys.zip -> appveyor.yml
